name: 'StellarStandards'
description: 'A github action that makes suggestions for improving your code in a given PR'
author: 'StellarStandards'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'Github authentication token needed to add comments to PRs'
    required: true

# Define your outputs here.
outputs:
  comment:
    description: 'The comment that was added to the PR (for testing purposes)'

runs:
  using: node20
  main: dist/index.js
